/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { Ierc20Mintable } from "./Ierc20Mintable";

export class Ierc20MintableFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Ierc20Mintable {
    return new Contract(address, _abi, signerOrProvider) as Ierc20Mintable;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256"
      }
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  }
];
