/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import { ILendingRateOracle } from "./ILendingRateOracle";

export class ILendingRateOracleFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILendingRateOracle {
    return new Contract(address, _abi, signerOrProvider) as ILendingRateOracle;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_asset",
        type: "address"
      }
    ],
    name: "getMarketBorrowRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_asset",
        type: "address"
      },
      {
        internalType: "uint256",
        name: "_rate",
        type: "uint256"
      }
    ],
    name: "setMarketBorrowRate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  }
];
