/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {Contract, ContractTransaction, EventFilter, Signer} from 'ethers';
import {Listener, Provider} from 'ethers/providers';
import {Arrayish, BigNumber, BigNumberish, Interface} from 'ethers/utils';
import {TransactionOverrides, TypedEventDescription, TypedFunctionDescription} from '.';

interface MockAggregatorLinkInterface extends Interface {
  functions: {
    latestAnswer: TypedFunctionDescription<{encode([]: []): string}>;
  };

  events: {
    AnswerUpdated: TypedEventDescription<{
      encodeTopics([current, roundId, timestamp]: [
        BigNumberish | null,
        BigNumberish | null,
        null
      ]): string[];
    }>;
  };
}

export class MockAggregatorLink extends Contract {
  connect(signerOrProvider: Signer | Provider | string): MockAggregatorLink;
  attach(addressOrName: string): MockAggregatorLink;
  deployed(): Promise<MockAggregatorLink>;

  on(event: EventFilter | string, listener: Listener): MockAggregatorLink;
  once(event: EventFilter | string, listener: Listener): MockAggregatorLink;
  addListener(eventName: EventFilter | string, listener: Listener): MockAggregatorLink;
  removeAllListeners(eventName: EventFilter | string): MockAggregatorLink;
  removeListener(eventName: any, listener: Listener): MockAggregatorLink;

  interface: MockAggregatorLinkInterface;

  functions: {
    latestAnswer(): Promise<BigNumber>;
  };

  latestAnswer(): Promise<BigNumber>;

  filters: {
    AnswerUpdated(
      current: BigNumberish | null,
      roundId: BigNumberish | null,
      timestamp: null
    ): EventFilter;
  };

  estimate: {
    latestAnswer(): Promise<BigNumber>;
  };
}
