import BigNumber from 'bignumber.js';
import {oneRay} from '../helpers/constants';
import {IAaveConfiguration} from '../helpers/types';

import {CommonsConfig} from './commons';

// ----------------
// POOL--SPECIFIC PARAMS
// ----------------

export const AaveConfig: IAaveConfiguration = {
  ...CommonsConfig,
  ConfigName: 'Aave',
  ProviderId: 1,
  ReserveSymbols: [
    'ETH',
    'DAI',
    'LEND',
    'TUSD',
    'BAT',
    'USDC',
    'USDT',
    'SUSD',
    'ZRX',
    'MKR',
    'WBTC',
    'LINK',
    'KNC',
    'MANA',
    'REP',
    'SNX',
    'BUSD',
  ],
  ReservesConfig: {
    DAI: {
      baseVariableBorrowRate: new BigNumber(0.01).multipliedBy(oneRay).toFixed(),
      variableRateSlope1: new BigNumber(0.05).multipliedBy(oneRay).toFixed(),
      variableRateSlope2: new BigNumber(0.5).multipliedBy(oneRay).toFixed(),
      stableRateSlope1: new BigNumber(0.16).multipliedBy(oneRay).toFixed(),
      stableRateSlope2: new BigNumber(0.6).multipliedBy(oneRay).toFixed(),
      baseLTVAsCollateral: '7500',
      liquidationThreshold: '8000',
      liquidationBonus: '10500',
      borrowingEnabled: true,
      stableBorrowRateEnabled: true,
      reserveDecimals: '18',
    },
    TUSD: {
      baseVariableBorrowRate: new BigNumber(0.01).multipliedBy(oneRay).toFixed(),
      variableRateSlope1: new BigNumber(0.04).multipliedBy(oneRay).toFixed(),
      variableRateSlope2: new BigNumber(0.5).multipliedBy(oneRay).toFixed(),
      stableRateSlope1: new BigNumber(0.14).multipliedBy(oneRay).toFixed(),
      stableRateSlope2: new BigNumber(0.6).multipliedBy(oneRay).toFixed(),
      baseLTVAsCollateral: '7500',
      liquidationThreshold: '8000',
      liquidationBonus: '10500',
      borrowingEnabled: true,
      stableBorrowRateEnabled: true,
      reserveDecimals: '18',
    },
    USDC: {
      baseVariableBorrowRate: new BigNumber(0.01).multipliedBy(oneRay).toFixed(),
      variableRateSlope1: new BigNumber(0.04).multipliedBy(oneRay).toFixed(),
      variableRateSlope2: new BigNumber(0.5).multipliedBy(oneRay).toFixed(),
      stableRateSlope1: new BigNumber(0.16).multipliedBy(oneRay).toFixed(),
      stableRateSlope2: new BigNumber(0.6).multipliedBy(oneRay).toFixed(),
      baseLTVAsCollateral: '7500',
      liquidationThreshold: '8000',
      liquidationBonus: '10500',
      borrowingEnabled: true,
      stableBorrowRateEnabled: true,
      reserveDecimals: '6',
    },
    USDT: {
      baseVariableBorrowRate: new BigNumber(0.01).multipliedBy(oneRay).toFixed(),
      variableRateSlope1: new BigNumber(0.04).multipliedBy(oneRay).toFixed(),
      variableRateSlope2: new BigNumber(0.5).multipliedBy(oneRay).toFixed(),
      stableRateSlope1: new BigNumber(0.14).multipliedBy(oneRay).toFixed(),
      stableRateSlope2: new BigNumber(0.6).multipliedBy(oneRay).toFixed(),
      baseLTVAsCollateral: '-1',
      liquidationThreshold: '8000',
      liquidationBonus: '10500',
      borrowingEnabled: true,
      stableBorrowRateEnabled: true,
      reserveDecimals: '6',
    },
    SUSD: {
      baseVariableBorrowRate: new BigNumber(0.01).multipliedBy(oneRay).toFixed(),
      variableRateSlope1: new BigNumber(0.04).multipliedBy(oneRay).toFixed(),
      variableRateSlope2: new BigNumber(0.5).multipliedBy(oneRay).toFixed(),
      stableRateSlope1: new BigNumber(0.14).multipliedBy(oneRay).toFixed(),
      stableRateSlope2: new BigNumber(0.6).multipliedBy(oneRay).toFixed(),
      baseLTVAsCollateral: '-1',
      liquidationThreshold: '8000',
      liquidationBonus: '10500',
      borrowingEnabled: true,
      stableBorrowRateEnabled: false,
      reserveDecimals: '18',
    },
    LEND: {
      baseVariableBorrowRate: new BigNumber(0).multipliedBy(oneRay).toFixed(),
      variableRateSlope1: new BigNumber(0.08).multipliedBy(oneRay).toFixed(),
      variableRateSlope2: new BigNumber(0.5).multipliedBy(oneRay).toFixed(),
      stableRateSlope1: new BigNumber(0.1).multipliedBy(oneRay).toFixed(),
      stableRateSlope2: new BigNumber(0.6).multipliedBy(oneRay).toFixed(),
      baseLTVAsCollateral: '6000',
      liquidationThreshold: '6500',
      liquidationBonus: '11500',
      borrowingEnabled: true,
      stableBorrowRateEnabled: true,
      reserveDecimals: '18',
    },
    BAT: {
      baseVariableBorrowRate: new BigNumber(0).multipliedBy(oneRay).toFixed(),
      variableRateSlope1: new BigNumber(0.08).multipliedBy(oneRay).toFixed(),
      variableRateSlope2: new BigNumber(0.5).multipliedBy(oneRay).toFixed(),
      stableRateSlope1: new BigNumber(0.1).multipliedBy(oneRay).toFixed(),
      stableRateSlope2: new BigNumber(0.6).multipliedBy(oneRay).toFixed(),
      baseLTVAsCollateral: '6000',
      liquidationThreshold: '6500',
      liquidationBonus: '11000',
      borrowingEnabled: true,
      stableBorrowRateEnabled: true,
      reserveDecimals: '18',
    },
    WETH: {
      baseVariableBorrowRate: new BigNumber(0).multipliedBy(oneRay).toFixed(),
      variableRateSlope1: new BigNumber(0.08).multipliedBy(oneRay).toFixed(),
      variableRateSlope2: new BigNumber(0.5).multipliedBy(oneRay).toFixed(),
      stableRateSlope1: new BigNumber(0.1).multipliedBy(oneRay).toFixed(),
      stableRateSlope2: new BigNumber(0.6).multipliedBy(oneRay).toFixed(),
      baseLTVAsCollateral: '7500',
      liquidationThreshold: '8000',
      liquidationBonus: '10500',
      borrowingEnabled: true,
      stableBorrowRateEnabled: true,
      reserveDecimals: '18',
    },
    LINK: {
      baseVariableBorrowRate: new BigNumber(0).multipliedBy(oneRay).toFixed(),
      variableRateSlope1: new BigNumber(0.08).multipliedBy(oneRay).toFixed(),
      variableRateSlope2: new BigNumber(0.5).multipliedBy(oneRay).toFixed(),
      stableRateSlope1: new BigNumber(0.1).multipliedBy(oneRay).toFixed(),
      stableRateSlope2: new BigNumber(0.6).multipliedBy(oneRay).toFixed(),
      baseLTVAsCollateral: '6500',
      liquidationThreshold: '7000',
      liquidationBonus: '11000',
      borrowingEnabled: true,
      stableBorrowRateEnabled: true,
      reserveDecimals: '18',
    },
    WBTC: {
      baseVariableBorrowRate: new BigNumber(0).multipliedBy(oneRay).toFixed(),
      variableRateSlope1: new BigNumber(0.08).multipliedBy(oneRay).toFixed(),
      variableRateSlope2: new BigNumber(0.5).multipliedBy(oneRay).toFixed(),
      stableRateSlope1: new BigNumber(0.1).multipliedBy(oneRay).toFixed(),
      stableRateSlope2: new BigNumber(0.6).multipliedBy(oneRay).toFixed(),
      baseLTVAsCollateral: '6000',
      liquidationThreshold: '6500',
      liquidationBonus: '11500',
      borrowingEnabled: true,
      stableBorrowRateEnabled: true,
      reserveDecimals: '8',
    },
    KNC: {
      baseVariableBorrowRate: new BigNumber(0).multipliedBy(oneRay).toFixed(),
      variableRateSlope1: new BigNumber(0.08).multipliedBy(oneRay).toFixed(),
      variableRateSlope2: new BigNumber(0.5).multipliedBy(oneRay).toFixed(),
      stableRateSlope1: new BigNumber(0.1).multipliedBy(oneRay).toFixed(),
      stableRateSlope2: new BigNumber(0.6).multipliedBy(oneRay).toFixed(),
      baseLTVAsCollateral: '6000',
      liquidationThreshold: '6500',
      liquidationBonus: '11000',
      borrowingEnabled: true,
      stableBorrowRateEnabled: true,
      reserveDecimals: '18',
    },
    REP: {
      baseVariableBorrowRate: new BigNumber(0).multipliedBy(oneRay).toFixed(),
      variableRateSlope1: new BigNumber(0.08).multipliedBy(oneRay).toFixed(),
      variableRateSlope2: new BigNumber(0.5).multipliedBy(oneRay).toFixed(),
      stableRateSlope1: new BigNumber(0.1).multipliedBy(oneRay).toFixed(),
      stableRateSlope2: new BigNumber(0.6).multipliedBy(oneRay).toFixed(),
      baseLTVAsCollateral: '6000',
      liquidationThreshold: '6500',
      liquidationBonus: '11000',
      borrowingEnabled: true,
      stableBorrowRateEnabled: true,
      reserveDecimals: '18',
    },
    MKR: {
      baseVariableBorrowRate: new BigNumber(0).multipliedBy(oneRay).toFixed(),
      variableRateSlope1: new BigNumber(0.08).multipliedBy(oneRay).toFixed(),
      variableRateSlope2: new BigNumber(0.5).multipliedBy(oneRay).toFixed(),
      stableRateSlope1: new BigNumber(0.1).multipliedBy(oneRay).toFixed(),
      stableRateSlope2: new BigNumber(0.6).multipliedBy(oneRay).toFixed(),
      baseLTVAsCollateral: '6000',
      liquidationThreshold: '6500',
      liquidationBonus: '11000',
      borrowingEnabled: true,
      stableBorrowRateEnabled: true,
      reserveDecimals: '18',
    },
    MANA: {
      baseVariableBorrowRate: new BigNumber(0).multipliedBy(oneRay).toFixed(),
      variableRateSlope1: new BigNumber(0.08).multipliedBy(oneRay).toFixed(),
      variableRateSlope2: new BigNumber(0.5).multipliedBy(oneRay).toFixed(),
      stableRateSlope1: new BigNumber(0.1).multipliedBy(oneRay).toFixed(),
      stableRateSlope2: new BigNumber(0.6).multipliedBy(oneRay).toFixed(),
      baseLTVAsCollateral: '6000',
      liquidationThreshold: '6500',
      liquidationBonus: '11000',
      borrowingEnabled: true,
      stableBorrowRateEnabled: true,
      reserveDecimals: '18',
    },
    ZRX: {
      baseVariableBorrowRate: new BigNumber(0).multipliedBy(oneRay).toFixed(),
      variableRateSlope1: new BigNumber(0.08).multipliedBy(oneRay).toFixed(),
      variableRateSlope2: new BigNumber(0.5).multipliedBy(oneRay).toFixed(),
      stableRateSlope1: new BigNumber(0.1).multipliedBy(oneRay).toFixed(),
      stableRateSlope2: new BigNumber(0.6).multipliedBy(oneRay).toFixed(),
      baseLTVAsCollateral: '6000',
      liquidationThreshold: '6500',
      liquidationBonus: '11000',
      borrowingEnabled: true,
      stableBorrowRateEnabled: true,
      reserveDecimals: '18',
    },
    SNX: {
      baseVariableBorrowRate: new BigNumber(0.03).multipliedBy(oneRay).toFixed(),
      variableRateSlope1: new BigNumber(0.12).multipliedBy(oneRay).toFixed(),
      variableRateSlope2: new BigNumber(0.5).multipliedBy(oneRay).toFixed(),
      stableRateSlope1: new BigNumber(0.1).multipliedBy(oneRay).toFixed(),
      stableRateSlope2: new BigNumber(0.6).multipliedBy(oneRay).toFixed(),
      baseLTVAsCollateral: '-1',
      liquidationThreshold: '6500',
      liquidationBonus: '11000',
      borrowingEnabled: true,
      stableBorrowRateEnabled: false,
      reserveDecimals: '18',
    },
    BUSD: {
      baseVariableBorrowRate: new BigNumber(0.01).multipliedBy(oneRay).toFixed(),
      variableRateSlope1: new BigNumber(0.04).multipliedBy(oneRay).toFixed(),
      variableRateSlope2: new BigNumber(0.5).multipliedBy(oneRay).toFixed(),
      stableRateSlope1: new BigNumber(0.14).multipliedBy(oneRay).toFixed(),
      stableRateSlope2: new BigNumber(0.6).multipliedBy(oneRay).toFixed(),
      baseLTVAsCollateral: '-1',
      liquidationThreshold: '8000',
      liquidationBonus: '11000',
      borrowingEnabled: true,
      stableBorrowRateEnabled: false,
      reserveDecimals: '18',
    },
  },
};

export default AaveConfig;
